.PHONY: all linear_actuator_bracket linear_actuator_bracket_side

all: linear_actuator_bracket linear_actuator_bracket_side 

linear_actuator_bracket:
	openscad linear_actuator_bracket.scad -o linear_actuator_bracket.stl --enable=fast-csg

linear_actuator_bracket_side:
	openscad linear_actuator_bracket_side.scad -o linear_actuator_bracket_side.stl --enable=fast-csg
